version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8000:3000'
  database:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5000:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
